package thermodynamics_test

import (
	"fmt"
	"math"
	"testing"
	"github.com/stephen-mcelhose/quantum-go/core"
	"github.com/stephen-mcelhose/quantum-go/local"
	smath "github.com/stephen-mcelhose/quantum-go/math"
)

// TestHadamardWork verifies that applying a Hadamard gate perform work
// equal to the change in expectation value of the Hamiltonian.
func TestHadamardWork(t *testing.T) {
	// 1. Define the Energy Landscape (Hamiltonian)
	// H = -B·σz (A qubit in a magnetic field)
	// Energy of |0> is -1, Energy of |1> is +1
	hamiltonian := smath.NewMatrix(2, 2)
	hamiltonian.Data = []complex128{
		-1, 0,
		0, 1,
	}

	e := local.NewSimpleExecutionEnvironment()
	p := core.NewProgram(1) // Starts in |0>
	
	// Initial Internal Energy U = <0|H|0> = -1
	res0 := e.RunProgram(p)
	rho0 := smath.ToDensityMatrix(res0.GetProbability())
	u0 := real(smath.ExpectationValue(rho0, hamiltonian))

	// 2. Perform Work using the Hadamard GATE
	// This rotates the state from |0> to |+>
	p.AddStep(core.NewStep(core.NewHadamard(0)))
	res1 := e.RunProgram(p)
	
	// Final Internal Energy U = <+|H|+> = 0.5(-1) + 0.5(1) = 0
	rho1 := smath.ToDensityMatrix(res1.GetProbability())
	u1 := real(smath.ExpectationValue(rho1, hamiltonian))

	workDone := u1 - u0
	
	fmt.Printf("Initial Energy (U0): %.2f\n", u0)
	fmt.Printf("Final Energy (U1):   %.2f\n", u1)
	fmt.Printf("Work Done (W):      %.2f\n", workDone)

	if workDone != 1.0 {
		t.Errorf("Expected Work = 1.0, got %v", workDone)
	}
}

// TestContinuousWork uses the TimeEvolution gate (generated by the Hamiltonian)
// to show how energy changes over time.
func TestContinuousWork(t *testing.T) {
	// Hamiltonian H = σx (Energy landscape that drives |0> -> |1>)
	hx := smath.NewMatrix(2, 2)
	hx.Data = []complex128{
		0, 1,
		1, 0,
	}
	
	// Observable Hamiltonian H_obs = σz (What we measure as "Energy")
	hz := smath.NewMatrix(2, 2)
	hz.Data = []complex128{1, 0, 0, -1}

	e := local.NewSimpleExecutionEnvironment()
	p := core.NewProgram(1)
	
	// Evolve for t = π/4
	// U(t) = exp(-i * Hx * t)
	evolution := core.NewTimeEvolution(0, hx, 3.14159/4.0)
	p.AddStep(core.NewStep(evolution))
	
	res := e.RunProgram(p)
	rho := smath.ToDensityMatrix(res.GetProbability())
	u_final := real(smath.ExpectationValue(rho, hz))
	
	// At t=π/4, |0> evolves to cos(π/4)|0> - i sin(π/4)|1>
	// Expected <Hz> = cos²(π/4) - sin²(π/4) = 0.5 - 0.5 = 0
	if math.Abs(u_final) > 1e-5 {
		t.Errorf("Expected energy 0 after evolution, got %v", u_final)
	}
}

// TestEntropy verifies Von Neumann entropy for pure and mixed states.
func TestEntropy(t *testing.T) {
	// Pure state |0> should have entropy 0
	rhoPure := smath.NewMatrix(2, 2)
	rhoPure.Data = []complex128{1, 0, 0, 0}
	s0 := smath.VonNeumannEntropy(rhoPure)
	if s0 > 1e-9 {
		t.Errorf("Expected pure state entropy 0, got %v", s0)
	}
	
	// Maximally mixed state I/2 should have entropy ln(2)
	rhoMixed := smath.NewMatrix(2, 2)
	rhoMixed.Data = []complex128{0.5, 0, 0, 0.5}
	s1 := smath.VonNeumannEntropy(rhoMixed)
	if fmt.Sprintf("%.4f", s1) != fmt.Sprintf("%.4f", 0.6931) { // ln(2) approx 0.6931
		t.Errorf("Expected mixed state entropy ln(2) ~0.6931, got %v", s1)
	}
}
